plugins:
  - jekyll-relative-links
  - no_intra_emphasis
  - autolink
  - tables
  - strikethrough
  - superscript
  - with_to_data
relative_links:
  enabled: true
  collections: true
include:
  - LICENSE.md
  - CONTRIBUTING.md

theme: jekyll-theme-tactile
show_downloads: false

title: "PPR IIDays 2023"
description: "Journée IID des PPRs affiliés ULaval"
